---
title: "mNGS pathogen identification script"
author: "Ali Al-Rashed"
date: "`r Sys.Date()`"
output: html_document
---

### Description

```{r}
library(data.table)
library(dplyr)
library(stringr)
```

## #Datasets available to use, all criteria has been applied and all are viral species

```{r}
kraken2_allsamples.fnl
centrifuge_allsamples.fnl.uniq
kaiju_allsamples.all
```

## Trim and combine into one dataset

```{r}
#first, remove all columns except filename, reads, taxid and name in preperation for the nested for loop
kraken2_allsamples.fnl.compressed<-kraken2_allsamples.fnl[,c(1,3,8,9)]
kraken2_allsamples.fnl.compressed$tool<- "kraken2"
colnames(kraken2_allsamples.fnl.compressed)<-c("FileName","reads","taxid","name","tool")

centrifuge_allsamples.fnl.uniq.compressed<-centrifuge_allsamples.fnl.uniq[,c(1,3,6,7)]
centrifuge_allsamples.fnl.uniq.compressed$tool<-"centrifuge"
colnames(centrifuge_allsamples.fnl.uniq.compressed)<-c("FileName","reads","taxid","name","tool")

kaiju_allsamples.all.compressed<-kaiju_allsamples.all[,c(1,3,4)]
kaiju_allsamples.all.compressed$name<-NA
kaiju_allsamples.all.compressed$tool<-"kaiju"
colnames(kaiju_allsamples.all.compressed)<-c("FileName","reads","taxid","name","tool")

#rowbind all
proposal.b.all<-rbind(kraken2_allsamples.fnl.compressed,centrifuge_allsamples.fnl.uniq.compressed,kaiju_allsamples.all.compressed)
proposal.b.all
```

## Overlap approach

```{r}
#now create a nested for loop
proposal.b.overlaptwice<-matrix(NA, ncol = 6)
colnames(proposal.b.overlaptwice)<-c("FileName","reads","taxid","name","tool","positive")
taxid.unique<-unique(proposal.b.all$taxid)
filenames<-unique(proposal.b.all$FileName)

for (i in filenames){
  for (o in taxid.unique) #I wanted to search for each taxon (in each sample) if it was classified by 2 or more classifiers
  {
    proposal.b.all.x<-proposal.b.all[proposal.b.all$FileName == i,]
    no.of.matches<-sum(proposal.b.all.x$taxid == o, na.rm = TRUE)
    atleast2matches<-no.of.matches>=2
    proposal.b.all.x.taxidonly<-proposal.b.all.x[proposal.b.all.x$taxid == o,]
    proposal.b.all.x.taxidonly$positive<-atleast2matches
    proposal.b.overlaptwice<-rbind(proposal.b.overlaptwice,proposal.b.all.x.taxidonly)
    rownumbers<-nrow(proposal.b.overlaptwice)
    rownames(proposal.b.overlaptwice)<-seq(rownumbers)
    proposal.b.overlaptwice<-proposal.b.overlaptwice[complete.cases(proposal.b.overlaptwice$tool),]
  }}
proposal.b.overlaptwice.postloop<-proposal.b.overlaptwice
proposal.b.overlaptwice.postloop<-proposal.b.overlaptwice.postloop[-is.na(proposal.b.overlaptwice.postloop),]
proposal.b.overlaptwice.postloop<-proposal.b.overlaptwice.postloop[proposal.b.overlaptwice.postloop$positive == TRUE,] #if a taxon is classified by 2 or more tools then TRUE

#Final stage proposal B = Proposal.b.FS
#How many unique taxids have at least two matches
#trim
Proposal.b.FS<-proposal.b.overlaptwice.postloop[,c(1,3,4,5)]

#create a for loop
Proposal.b.FS.unique<-matrix(NA, ncol = 4)
colnames(Proposal.b.FS.unique)<-colnames(Proposal.b.FS)
filenames<-unique(Proposal.b.FS$FileName)

for (i in filenames) {
  Proposal.b.FS.x<-Proposal.b.FS[Proposal.b.FS$FileName == i,]
  Proposal.b.FS.x<-Proposal.b.FS.x[!duplicated(Proposal.b.FS.x$taxid),]
  Proposal.b.FS.unique<-rbind(Proposal.b.FS.unique,Proposal.b.FS.x)
}
Proposal.b.FS.unique.v.species<-Proposal.b.FS.unique
Proposal.b.FS.unique.v.species<-Proposal.b.FS.unique.v.species[-is.na(Proposal.b.FS.unique.v.species),]
```


## Re-add metrics and process further

```{r}
#re-add kraken2, centrifuge and kaiju metrics
#avalibale sets to used
Proposal.b.FS.unique.v.species
kraken2_allsamples.fnl
centrifuge_allsamples.fnl.uniq 
kaiju_allsamples.all 
krakenuniq_allsamples.v 

#create a for loop to add all datasets at once
Proposal.b.FS.unique2.v.species.full<-matrix(NA, ncol = 34)
colnames(Proposal.b.FS.unique2.v.species.full)<-c("Filename", "taxid","name","tool","k.FileName","k.%","k.reads_covered_by_taxon" , "k.reads_assigned_to_taxon" ,"k.minimizer_count", 
                                                  "k.minimizer_unique"      , 
                                                  "k.rank","k.name","k.rownumber","k.rpm",
                                                  "c.FileName","c.%","c.reads_covered_by_taxon", "c.reads_assigned_to_taxon" ,"c.rank",
                                                  "c.name","c.rownumber", "c.rpm", "c.uniquereads", "kj.FileName", "kj.%", "kj.reads", "kj.totalreads", "kj.rpm", 
                                                  "ku.FileName", "ku.%","ku.reads","ku.kmer", "ku.dup","ku.cov")
sample.names<-unique(Proposal.b.FS.unique.v.species$FileName)


for (i in sample.names){
  step.1<-Proposal.b.FS.unique.v.species[Proposal.b.FS.unique.v.species$FileName == i,]
  step.2<-kraken2_allsamples.fnl[kraken2_allsamples.fnl$FileName == i,]
  step.3<-centrifuge_allsamples.fnl.uniq[centrifuge_allsamples.fnl.uniq$FileName == i,]
  step.4<-kaiju_allsamples.all[kaiju_allsamples.all$FileName == i,]
  step.5<-filter(krakenuniq_allsamples.v, FileName == i)
  step.5<-step.5[,c(1,2,3,5,6,7,8)]
  join1<-left_join(step.1,step.2,by = "taxid")
  join2<-left_join(join1,step.3,by = "taxid")
  join3<-left_join(join2,step.4,by="taxid")
  join4<-left_join(join3,step.5, by = c("taxid" = "taxID"))
  colnames(join4)<-colnames(Proposal.b.FS.unique2.v.species.full)
  Proposal.b.FS.unique2.v.species.full<-rbind(Proposal.b.FS.unique2.v.species.full,join4)
}
Proposal.b.FS.unique2.v.species.full<-Proposal.b.FS.unique2.v.species.full[complete.cases(Proposal.b.FS.unique2.v.species.full$Filename),]
Proposal.b.FS.unique2.v.species.full<-Proposal.b.FS.unique2.v.species.full[,-4]

#combine rpm columns into one and then divide by the number of tool matches
Proposal.b.FS.unique2.v.species.full$rpm<-rowSums(Proposal.b.FS.unique2.v.species.full[ , c("k.rpm","c.rpm","kj.rpm")], na.rm=TRUE)

#create a new column to show how many tools have classified this taxon
#for one sample
Proposal.b.FS.unique2.v.species.full$kraken2match<-complete.cases(Proposal.b.FS.unique2.v.species.full$k.FileName)
Proposal.b.FS.unique2.v.species.full$centrifugematch<-complete.cases(Proposal.b.FS.unique2.v.species.full$c.FileName)
Proposal.b.FS.unique2.v.species.full$kaijumatch<-complete.cases(Proposal.b.FS.unique2.v.species.full$kj.FileName)

Proposal.b.FS.unique2.v.species.full$tools<-rowSums(Proposal.b.FS.unique2.v.species.full[ , c("centrifugematch","kraken2match",
                                                                                              "kaijumatch")], na.rm=TRUE)

Proposal.b.FS.unique2.v.species.full$adjustedrpm<- Proposal.b.FS.unique2.v.species.full$rpm / Proposal.b.FS.unique2.v.species.full$tools
Proposal.b.FS.unique2.v.species.full[is.na(Proposal.b.FS.unique2.v.species.full$adjustedrpm),]

#########
#create a new column with distint sample name
Proposal.b.FS.unique2.v.species.full$Filename
Proposal.b.FS.unique2.v.species.full$uniquefilename1<-
  as.numeric(gsub("D", "", Proposal.b.FS.unique2.v.species.full$Filename))
Proposal.b.FS.unique2.v.species.full$uniquefilename2<-
  as.numeric(gsub("R", "", Proposal.b.FS.unique2.v.species.full$Filename))

Proposal.b.FS.unique2.v.species.full$uniquefilename<-paste(Proposal.b.FS.unique2.v.species.full$uniquefilename1,
                                                           Proposal.b.FS.unique2.v.species.full$uniquefilename2)
Proposal.b.FS.unique2.v.species.full$uniquefilename<-  
  as.character(gsub("NA", "", Proposal.b.FS.unique2.v.species.full$uniquefilename))
```

## overlap with human viral pathogen list

```{r}
pathogens.list<-read.csv('chan.id.viruses.list.csv')
row_odd <- seq_len(nrow(pathogens.list)) %% 2 
data_row_even <- pathogens.list[row_odd == 0, ]   
data_row_odd <- pathogens.list[row_odd == 1, ]   
pathogens.list<-data.frame(name = data_row_odd, taxid = data_row_even)
pathogens.list$taxid<-str_trim(pathogens.list$taxid)
pathogens.list$taxid <- sapply(pathogens.list$taxid, as.numeric )
pathogens.list$human_pathogenic<-"yes"

#overlap to see if any of the species after applying criteria are human pathogenic
species.3rd.humanpathogens<-Proposal.b.FS.unique2.v.species.full[Proposal.b.FS.unique2.v.species.full$taxid %in% pathogens.list$taxid,]
nrow(species.3rd.humanpathogens)

#remove DBS control sample only
species.3rd.humanpathogens.samplesonly<-species.3rd.humanpathogens[!species.3rd.humanpathogens$Filename == "D13",]
species.3rd.humanpathogens.samplesonly<-species.3rd.humanpathogens.samplesonly[!species.3rd.humanpathogens.samplesonly$Filename == "R13",]
nrow(species.3rd.humanpathogens.samplesonly)
unique(select(species.3rd.humanpathogens.samplesonly, c(taxid,name)))
```

